# Generated by Django 6.0 on 2025-12-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
    ]
