# Generated by Django 6.0 on 2025-12-28 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, verbose_name='number')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='amount')),
                ('signing_date', models.DateField(verbose_name='date_signing')),
                ('site_handover_date', models.DateField(blank=True, null=True, verbose_name='date_receipt_site')),
                ('actual_start_date', models.DateField(blank=True, null=True, verbose_name='date_handover_site')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='duration')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('is_suspended', models.BooleanField(default=False, verbose_name='is_suspended')),
                ('percent10', models.BooleanField(default=False, verbose_name='percent10')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='companies.company')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='departments.department')),
            ],
            options={
                'db_table': 'contracts',
            },
        ),
    ]
