# Generated by Django 6.0 on 2025-12-28 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contract_transaction_types', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTransactionRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_transaction_requirements', to='contract_transaction_types.contracttransactiontype')),
            ],
            options={
                'db_table': 'contract_transaction_requirements',
            },
        ),
    ]
