# Generated by Django 6.0 on 2025-12-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('path', models.TextField(verbose_name='path')),
                ('status', models.CharField(choices=[('under_review', 'Under Review'), ('unacceptable', 'Unacceptable'), ('certified', 'Certified')], max_length=20)),
            ],
            options={
                'db_table': 'contract_files',
            },
        ),
    ]
