"""
Django settings for tawtheeq project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", cast=bool)

ALLOWED_HOSTS = config("ALLOWED_HOSTS").split(",")


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users.apps.UsersConfig',
    'helpers.apps.HelpersConfig',
    'agents.apps.AgentsConfig',
    'departments.apps.DepartmentsConfig',
    'companies.apps.CompaniesConfig',
    'contracts.apps.ContractsConfig',
    'contract_suspension_periods.apps.ContractSuspensionPeriodsConfig',
    'contract_transaction_types.apps.ContractTransactionTypesConfig',
    'contract_transaction_requirements.apps.ContractTransactionRequirementsConfig',
    'contract_files.apps.ContractFilesConfig',
    'contract_transactions.apps.ContractTransactionsConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tawtheeq.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tawtheeq.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ar'

TIME_ZONE = 'Asia/Riyadh'

USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_ROOT = BASE_DIR / "staticfiles"

STATIC_URL = 'static/'

STATICFILES_DIRS = [BASE_DIR / "static"]

AUTH_USER_MODEL = 'users.User'

JAZZMIN_SETTINGS = {
    # Title & Header
    "site_title": "أمانة العاصمة المقدسة",
    "site_header": "أمانة العاصمة المقدسة",
    "site_brand": "أمانة العاصمة المقدسة",
    "custom_css": "jazzmin/css/jazzmin_custom.css",

    # Logo
    "site_logo": "site/img/logo-white.png",
    "site_logo_classes": "elevation-3",
    "site_icon": "site/img/fav.png",
    # Welcome
    "welcome_sign": "مرحبا بك في أمانة العاصمة المقدسة",

    # Footer
    "copyright": "أمانة العاصمة المقدسة © 2025",

    # Search
    "search_model": ["users.User", "auth.Group"],

    # User Menu
    # "usermenu_links": [
    #     {"name": "Home", "url": "/", "icon": "fas fa-home"},
    #     {"name": "Support", "url": "https://example.com", "new_window": True},
    # ],

    # Top Menu
    "topmenu_links": [
        {"name": "Dashboard", "url": "admin:index", "permissions": ["auth.view_user"]},
    ],

    # Sidebar
    # "show_sidebar": True,
    # "navigation_expanded": True,

    # Order Apps
    # "order_with_respect_to": ["bridges", "accounts", "auth"],

    # Icons
    "icons": {
        # "auth": "fas fa-users-cog",
        "users.user": "fas fa-user",
        "auth.group": "fas fa-user-shield",
        # "bridges.bridge": "fas fa-bridge",
    },

    # Hide models
    # "hide_models": ["auth.permission"],

    # UI Tweaks
    "related_modal_active": True,
}

JAZZMIN_UI_TWEAKS = {
     "rtl": True,
#     "theme": "cosmo",     # darkly / flatly / minty / cosmo
#     "dark_mode_theme": "cosmo",

#     "navbar": "navbar-dark bg-transparent",
#     "sidebar": "sidebar-dark-transparent",
#     "accent": "accent-primary",

#     "brand_colour": "navbar-transparent",

#     "button_classes": {
#         "primary": "btn-primary",
#         "secondary": "btn-secondary",
#         "info": "btn-info",
#         "warning": "btn-warning",
#         "danger": "btn-danger",
#         "success": "btn-success",
#     },
}