# Generated by Django 6.0 on 2025-12-22 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('cr_number', models.IntegerField(blank=True, null=True, verbose_name='cr_number')),
                ('cr_expiry', models.DateField(blank=True, null=True, verbose_name='cr_expiry')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='phone')),
                ('mobile', models.CharField(blank=True, max_length=15, null=True, verbose_name='mobile')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='email')),
                ('website', models.CharField(blank=True, max_length=255, null=True, verbose_name='website')),
                ('address', models.TextField(blank=True, null=True, verbose_name='address')),
                ('type', models.CharField(choices=[('contractor', 'Contractor'), ('consultant', 'Consultant')], max_length=20)),
            ],
        ),
    ]
