# Generated by Django 6.0 on 2026-01-01 11:44

import chats.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=chats.models.sa_now, editable=False)),
            ],
            options={
                'db_table': 'chats',
                'ordering': ['created_at'],
            },
        ),
    ]
