# Generated by Django 6.0 on 2025-12-28 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractSuspensionPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(verbose_name='from_date')),
                ('to_date', models.DateField(blank=True, null=True, verbose_name='to_date')),
                ('reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='reason')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspension_periods', to='contracts.contract')),
            ],
            options={
                'db_table': 'contract_suspension_periods',
            },
        ),
    ]
