# Generated by Django 6.0 on 2025-12-21 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='parent_id',
            new_name='parent',
        ),
    ]
