# Generated by Django 6.0 on 2025-12-28 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contract_transaction_types', '0001_initial'),
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('incoming_number', models.TextField(blank=True, max_length=255, null=True, verbose_name='incoming_number')),
                ('extract_number', models.TextField(blank=True, max_length=255, null=True, verbose_name='extract_number')),
                ('subject', models.TextField(blank=True, null=True, verbose_name='subject')),
                ('is_documented', models.BooleanField(default=False, verbose_name='is_documented')),
                ('documentation_number', models.TextField(blank=True, max_length=255, null=True, verbose_name='documentation_number')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_transactions', to='contracts.contract')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_transactions', to='contract_transaction_types.contracttransactiontype')),
            ],
            options={
                'db_table': 'contract_transactions',
            },
        ),
    ]
